Resources:
  AnimalTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.animalTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: animalId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: animalId
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}